---

- name: Network Getting Started First Playbook
  hosts: routers
  tasks:

  - name: Get config for Cisco devices
    cisco.ios.ios_facts:
      gather_subset: all

  - name: Display the config
    debug:
      msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

